
import type { Restaurant, Offer, Order, Review, WalletTransaction } from './types';

export const restaurants: Restaurant[] = [
  {
    id: '1',
    name: 'Royal Spice',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'North Indian, Mughlai',
    rating: 4.7,
    deliveryTime: 30,
    priceRange: 'moderate',
    priceForTwo: 750,
    promotion: '15% off above ₹799',
    reviews: '3.2k+',
    location: 'Indiranagar',
    distance: 4.5,
    opensAt: '11:00 AM',
    tags: ['Best In North Indian'],
  },
  {
    id: '2',
    name: 'Pizza Heaven',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Pizza, Italian',
    rating: 4.4,
    deliveryTime: 25,
    priceRange: 'cheap',
    priceForTwo: 500,
    reviews: '2.8k+',
    location: 'Koramangala',
    distance: 3.1,
    opensAt: '12:00 PM',
    promotion: 'BOGO on Medium Pizza'
  },
  {
    id: '3',
    name: 'Wok & Roll',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Chinese, Thai',
    rating: 4.6,
    deliveryTime: 45,
    priceRange: 'moderate',
    priceForTwo: 800,
    reviews: '1.5k+',
    location: 'Jayanagar',
    distance: 2.5,
    opensAt: '12:00 PM',
  },
  {
    id: '4',
    name: 'Burger Barn',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'American',
    rating: 4.0,
    deliveryTime: 20,
    priceRange: 'cheap',
    priceForTwo: 400,
    reviews: '900+',
    location: 'Malleshwaram',
    distance: 5.2,
    opensAt: '10:00 AM',
  },
  {
    id: '5',
    name: 'Curry House',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Indian',
    rating: 4.6,
    deliveryTime: 35,
    priceRange: 'moderate',
    priceForTwo: 650,
    promotion: 'Free naan bread',
    reviews: '2.1k+',
    location: 'HSR Layout',
    distance: 6.0,
    opensAt: '11:30 AM',
  },
  {
    id: '6',
    name: 'Peking Duck',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Chinese',
    rating: 4.3,
    deliveryTime: 50,
    priceRange: 'expensive',
    priceForTwo: 1800,
    reviews: '850+',
    location: 'Whitefield',
    distance: 10.5,
    opensAt: '12:30 PM',
  },
  {
    id: '7',
    name: 'Mom\'s Kitchen',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'North Indian, Home Food',
    rating: 4.9,
    deliveryTime: 40,
    priceRange: 'moderate',
    priceForTwo: 600,
    promotion: '10% off on first order',
    reviews: '1.2k+',
    location: 'Indiranagar',
    distance: 4.2,
    opensAt: '09:00 AM',
    tags: ['Homemade', 'Healthy'],
  },
  {
    id: '8',
    name: 'Desi Delights',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'South Indian, Home Food',
    rating: 4.8,
    deliveryTime: 35,
    priceRange: 'cheap',
    priceForTwo: 300,
    reviews: '980+',
    location: 'Koramangala',
    distance: 3.5,
    opensAt: '08:00 AM',
    tags: ['Homemade'],
  },
  {
    id: '9',
    name: 'Taco Town',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Mexican',
    rating: 4.5,
    deliveryTime: 30,
    priceRange: 'moderate',
    priceForTwo: 700,
    reviews: '1.1k+',
    location: 'Indiranagar',
    distance: 4.0,
    opensAt: '12:00 PM',
  },
  {
    id: '10',
    name: 'Sushi Central',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Japanese',
    rating: 4.8,
    deliveryTime: 55,
    priceRange: 'expensive',
    priceForTwo: 2500,
    reviews: '750+',
    location: 'MG Road',
    distance: 6.5,
    opensAt: '01:00 PM',
  },
  {
    id: '11',
    name: 'The Dosa Hub',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'South Indian',
    rating: 4.6,
    deliveryTime: 20,
    priceRange: 'cheap',
    priceForTwo: 250,
    reviews: '4.5k+',
    location: 'Jayanagar',
    distance: 2.0,
    opensAt: '07:00 AM',
  },
  {
    id: '12',
    name: 'Kebab Korner',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Mughlai, Kebab',
    rating: 4.4,
    deliveryTime: 35,
    priceRange: 'moderate',
    priceForTwo: 850,
    reviews: '2.5k+',
    location: 'Koramangala',
    distance: 3.8,
    opensAt: '12:30 PM',
  },
  {
    id: '13',
    name: 'Pasta Point',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Italian, Pasta',
    rating: 4.3,
    deliveryTime: 40,
    priceRange: 'moderate',
    priceForTwo: 900,
    promotion: '20% off on pasta bowls',
    reviews: '1.8k+',
    location: 'HSR Layout',
    distance: 5.5,
    opensAt: '11:00 AM',
  },
  {
    id: '14',
    name: 'Biryani Blues',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Biryani, North Indian',
    rating: 4.7,
    deliveryTime: 30,
    priceRange: 'moderate',
    priceForTwo: 700,
    reviews: '5.1k+',
    location: 'Marathahalli',
    distance: 8.0,
    opensAt: '12:00 PM',
  },
  {
    id: '15',
    name: 'Healthy Bites',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Salads, Healthy Food',
    rating: 4.9,
    deliveryTime: 25,
    priceRange: 'moderate',
    priceForTwo: 600,
    reviews: '950+',
    location: 'Indiranagar',
    distance: 4.8,
    opensAt: '10:00 AM',
    tags: ['Healthy'],
  },
  {
    id: '16',
    name: 'The Sandwich Shop',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'American, Fast Food',
    rating: 4.2,
    deliveryTime: 15,
    priceRange: 'cheap',
    priceForTwo: 350,
    reviews: '1.4k+',
    location: 'Jayanagar',
    distance: 2.2,
    opensAt: '09:00 AM',
  },
  {
    id: '17',
    name: 'Thai Chi',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Thai, Asian',
    rating: 4.5,
    deliveryTime: 45,
    priceRange: 'expensive',
    priceForTwo: 1600,
    reviews: '1.3k+',
    location: 'Koramangala',
    distance: 3.3,
    opensAt: '01:00 PM',
  },
  {
    id: '18',
    name: 'Greek Goddess',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Mediterranean, Greek',
    rating: 4.6,
    deliveryTime: 50,
    priceRange: 'expensive',
    priceForTwo: 2000,
    reviews: '650+',
    location: 'Indiranagar',
    distance: 5.0,
    opensAt: '12:30 PM',
  },
  {
    id: '19',
    name: 'Paratha Palace',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'North Indian',
    rating: 4.3,
    deliveryTime: 25,
    priceRange: 'cheap',
    priceForTwo: 300,
    reviews: '3.8k+',
    location: 'HSR Layout',
    distance: 5.8,
    opensAt: '08:00 AM',
  },
  {
    id: '20',
    name: 'Falafel King',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Lebanese, Middle Eastern',
    rating: 4.4,
    deliveryTime: 35,
    priceRange: 'moderate',
    priceForTwo: 650,
    reviews: '1.7k+',
    location: 'Koramangala',
    distance: 3.0,
    opensAt: '11:30 AM',
  },
  {
    id: '21',
    name: 'Chai Point',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Beverages, Fast Food',
    rating: 4.5,
    deliveryTime: 15,
    priceRange: 'cheap',
    priceForTwo: 200,
    reviews: '6.2k+',
    location: 'Multiple',
    distance: 1.5,
    opensAt: '07:00 AM',
  },
  {
    id: '22',
    name: 'Sweet Tooth',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Desserts, Bakery',
    rating: 4.7,
    deliveryTime: 30,
    priceRange: 'moderate',
    priceForTwo: 500,
    reviews: '2.9k+',
    location: 'Indiranagar',
    distance: 4.6,
    opensAt: '10:00 AM',
  },
  {
    id: '23',
    name: 'Coastal Curry',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Seafood, Mangalorean',
    rating: 4.6,
    deliveryTime: 40,
    priceRange: 'expensive',
    priceForTwo: 1900,
    reviews: '1.1k+',
    location: 'Koramangala',
    distance: 3.9,
    opensAt: '12:00 PM',
  },
  {
    id: '24',
    name: 'Rolls Mania',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Rolls, Fast Food',
    rating: 4.2,
    deliveryTime: 20,
    priceRange: 'cheap',
    priceForTwo: 250,
    reviews: '4.1k+',
    location: 'Jayanagar',
    distance: 2.8,
    opensAt: '11:00 AM',
  },
  {
    id: '25',
    name: 'The Breakfast Club',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Continental, American',
    rating: 4.8,
    deliveryTime: 35,
    priceRange: 'moderate',
    priceForTwo: 1000,
    reviews: '3.5k+',
    location: 'Indiranagar',
    distance: 4.3,
    opensAt: '08:30 AM',
  },
  {
    id: '26',
    name: 'Noodle Bar',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Chinese, Pan-Asian',
    rating: 4.4,
    deliveryTime: 30,
    priceRange: 'moderate',
    priceForTwo: 950,
    reviews: '2.3k+',
    location: 'HSR Layout',
    distance: 5.2,
    opensAt: '12:00 PM',
  },
  {
    id: '27',
    name: 'Grandma\'s Cafe',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Cafe, Italian',
    rating: 4.6,
    deliveryTime: 40,
    priceRange: 'moderate',
    priceForTwo: 1100,
    reviews: '1.9k+',
    location: 'Koramangala',
    distance: 3.6,
    opensAt: '09:00 AM',
  },
  {
    id: '28',
    name: 'Steak House',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'American, Steak',
    rating: 4.7,
    deliveryTime: 50,
    priceRange: 'expensive',
    priceForTwo: 3000,
    reviews: '800+',
    location: 'MG Road',
    distance: 6.8,
    opensAt: '06:00 PM',
  },
  {
    id: '29',
    name: 'Just Juice',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Juices, Healthy Food',
    rating: 4.5,
    deliveryTime: 15,
    priceRange: 'cheap',
    priceForTwo: 200,
    reviews: '2.2k+',
    location: 'Jayanagar',
    distance: 2.1,
    opensAt: '10:00 AM',
    tags: ['Healthy'],
  },
  {
    id: '30',
    name: 'BBQ Nation',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Barbecue, North Indian',
    rating: 4.9,
    deliveryTime: 60,
    priceRange: 'expensive',
    priceForTwo: 2200,
    reviews: '7.8k+',
    location: 'Indiranagar',
    distance: 5.1,
    opensAt: '12:30 PM',
  },
  {
    id: '31',
    name: 'Punjabi Tadka',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'North Indian, Punjabi',
    rating: 4.3,
    deliveryTime: 35,
    priceRange: 'moderate',
    priceForTwo: 750,
    reviews: '3.1k+',
    location: 'BTM Layout',
    distance: 4.5,
    opensAt: '11:00 AM',
  },
  {
    id: '32',
    name: 'Empire Restaurant',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'North Indian, Kebab, Biryani',
    rating: 4.1,
    deliveryTime: 30,
    priceRange: 'cheap',
    priceForTwo: 500,
    reviews: '10k+',
    location: 'Multiple',
    distance: 2.5,
    opensAt: '12:00 PM',
  },
  {
    id: '33',
    name: 'Truffles',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'American, Burger, Cafe',
    rating: 4.6,
    deliveryTime: 45,
    priceRange: 'moderate',
    priceForTwo: 900,
    reviews: '8.5k+',
    location: 'Koramangala',
    distance: 3.2,
    opensAt: '11:00 AM',
  },
  {
    id: '34',
    name: 'Meghana Foods',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Biryani, Andhra',
    rating: 4.5,
    deliveryTime: 25,
    priceRange: 'moderate',
    priceForTwo: 800,
    reviews: '9.2k+',
    location: 'Jayanagar',
    distance: 2.9,
    opensAt: '12:00 PM',
  },
  {
    id: '35',
    name: 'Corner House Ice Creams',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Ice Cream, Desserts',
    rating: 4.8,
    deliveryTime: 20,
    priceRange: 'cheap',
    priceForTwo: 300,
    reviews: '5.5k+',
    location: 'Multiple',
    distance: 1.8,
    opensAt: '10:00 AM',
  },
  {
    id: '36',
    name: 'Onesta',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Pizza, Italian, Desserts',
    rating: 4.2,
    deliveryTime: 50,
    priceRange: 'moderate',
    priceForTwo: 700,
    reviews: '4.8k+',
    location: 'Indiranagar',
    distance: 4.9,
    opensAt: '12:30 PM',
  },
  {
    id: '37',
    name: 'The Hole in the Wall Cafe',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Cafe, American, Breakfast',
    rating: 4.7,
    deliveryTime: 40,
    priceRange: 'moderate',
    priceForTwo: 800,
    reviews: '6.9k+',
    location: 'Koramangala',
    distance: 3.4,
    opensAt: '08:00 AM',
  },
  {
    id: '38',
    name: 'Leon Grill',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Burger, Wraps, Turkish',
    rating: 4.3,
    deliveryTime: 25,
    priceRange: 'cheap',
    priceForTwo: 450,
    reviews: '7.2k+',
    location: 'HSR Layout',
    distance: 5.0,
    opensAt: '11:00 AM',
  },
  {
    id: '39',
    name: 'Chetana Veg Restaurant',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'North Indian, Gujarati',
    rating: 4.0,
    deliveryTime: 0, 
    priceRange: 'expensive',
    promotion: 'Flat 10% off on pre-booking',
    reviews: '1.2k+',
    location: 'Fort',
    distance: 5.3,
    opensAt: '12:00 PM',
    tags: ['Dine-in Special'],
    priceForTwo: 1200,
    extraOffer: '1 offer'
  },
  {
    id: '40',
    name: 'Caffe Allora',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Italian, Beverages',
    rating: 4.2,
    deliveryTime: 0,
    priceRange: 'expensive',
    promotion: 'Flat 15% off',
    reviews: '800+',
    location: 'Phoenix Palladium',
    distance: 7.0,
    opensAt: '11:00 AM',
    tags: ['Dine-in Special'],
    priceForTwo: 1500,
  },
  {
    id: '41',
    name: 'Global Fusion',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Pan-Asian, Buffet',
    rating: 4.5,
    deliveryTime: 0,
    priceRange: 'expensive',
    promotion: '20% off on buffet',
    reviews: '2.5k+',
    location: 'Bandra',
    distance: 8.2,
    opensAt: '12:00 PM',
    tags: ['Dine-in Special'],
    priceForTwo: 3000,
  },
  {
    id: '42',
    name: 'The Table',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'European, Continental',
    rating: 4.8,
    deliveryTime: 0,
    priceRange: 'expensive',
    promotion: 'Complimentary dessert',
    reviews: '1.8k+',
    location: 'Colaba',
    distance: 6.1,
    opensAt: '01:00 PM',
    tags: ['Dine-in Special'],
    priceForTwo: 4000,
  },
  {
    id: '43',
    name: 'Bademiya',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Kebab, North Indian',
    rating: 4.3,
    deliveryTime: 0,
    priceRange: 'moderate',
    promotion: 'Free soft drink',
    reviews: '5.2k+',
    location: 'Colaba',
    distance: 6.3,
    opensAt: '06:00 PM',
    tags: ['Dine-in Special'],
    priceForTwo: 900,
  },
  {
    id: '44',
    name: 'PVR Cafe',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Fast Food, Beverages',
    rating: 4.6,
    deliveryTime: 0,
    priceRange: 'expensive',
    promotion: '15% off on food bill',
    reviews: '1.5k+',
    location: 'PVR, BKC',
    distance: 9.5,
    opensAt: '12:00 PM',
    tags: ['Dine-in Special', 'Movie Theatre'],
    priceForTwo: 1200,
  },
  {
    id: '45',
    name: 'INOX Insignia',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Continental, Desserts',
    rating: 4.7,
    deliveryTime: 0,
    priceRange: 'expensive',
    promotion: 'Special tasting menu',
    reviews: '2.1k+',
    location: 'INOX, BKC',
    distance: 9.8,
    opensAt: '12:00 PM',
    tags: ['Dine-in Special', 'Movie Theatre'],
    priceForTwo: 1800,
  },
  {
    id: '46',
    name: 'Britannia & Co.',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Parsi, Iranian',
    rating: 4.5,
    deliveryTime: 0,
    priceRange: 'moderate',
    reviews: '3.5k+',
    location: 'Ballard Estate',
    distance: 4.8,
    opensAt: '12:00 PM',
    tags: ['Dine-in Special'],
    priceForTwo: 1000,
  },
  {
    id: '47',
    name: 'The Bombay Canteen',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Modern Indian',
    rating: 4.6,
    deliveryTime: 0,
    priceRange: 'expensive',
    reviews: '2.8k+',
    location: 'Lower Parel',
    distance: 7.5,
    opensAt: '12:00 PM',
    tags: ['Dine-in Special'],
    priceForTwo: 2000,
  },
  {
    id: '48',
    name: 'Cinepolis Coffee Tree',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Cafe, Fast Food',
    rating: 4.4,
    deliveryTime: 0,
    priceRange: 'expensive',
    reviews: '2.2k+',
    location: 'Cinepolis, Fort',
    distance: 5.5,
    opensAt: '12:00 PM',
    tags: ['Dine-in Special', 'Movie Theatre'],
    priceForTwo: 900,
  },
  {
    id: '49',
    name: 'O Pedro',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Goan, Portuguese',
    rating: 4.5,
    deliveryTime: 0,
    priceRange: 'expensive',
    reviews: '1.9k+',
    location: 'BKC',
    distance: 9.6,
    opensAt: '12:00 PM',
    tags: ['Dine-in Special'],
    priceForTwo: 2200,
  },
  {
    id: '50',
    name: 'Gajalee',
    image: 'https://placehold.co/600x400.png',
    cuisine: 'Seafood, Maharashtrian',
    rating: 4.3,
    deliveryTime: 0,
    priceRange: 'expensive',
    reviews: '2.7k+',
    location: 'Vile Parle',
    distance: 12.0,
    opensAt: '11:30 AM',
    tags: ['Dine-in Special'],
    priceForTwo: 1800,
  },
  // 20 New Homemade Kitchens
  { id: '51', name: 'Anita\'s Kitchen', image: 'https://placehold.co/600x400.png', cuisine: 'Home Food, North Indian', rating: 4.8, deliveryTime: 30, priceRange: 'moderate', priceForTwo: 450, reviews: '150+', location: 'Jayanagar', distance: 2.8, opensAt: '09:00 AM', tags: ['Homemade'] },
  { id: '52', name: 'Raj\'s Gourmet', image: 'https://placehold.co/600x400.png', cuisine: 'Home Food, Continental', rating: 4.9, deliveryTime: 45, priceRange: 'moderate', priceForTwo: 700, reviews: '95+', location: 'Koramangala', distance: 3.0, opensAt: '12:00 PM', tags: ['Homemade', 'Healthy'] },
  { id: '53', name: 'The Sharma Kitchenette', image: 'https://placehold.co/600x400.png', cuisine: 'Home Food, Punjabi', rating: 4.7, deliveryTime: 40, priceRange: 'moderate', priceForTwo: 550, reviews: '210+', location: 'Indiranagar', distance: 4.5, opensAt: '11:00 AM', tags: ['Homemade'] },
  { id: '54', name: 'Gupta\'s Ghar Ka Khana', image: 'https://placehold.co/600x400.png', cuisine: 'Home Food, Rajasthani', rating: 4.8, deliveryTime: 35, priceRange: 'cheap', priceForTwo: 400, reviews: '180+', location: 'HSR Layout', distance: 5.5, opensAt: '10:00 AM', tags: ['Homemade'] },
  { id: '55', name: 'Priya\'s Parathas', image: 'https://placehold.co/600x400.png', cuisine: 'Home Food, North Indian', rating: 4.9, deliveryTime: 25, priceRange: 'cheap', priceForTwo: 250, reviews: '350+', location: 'BTM Layout', distance: 4.0, opensAt: '08:00 AM', tags: ['Homemade'] },
  { id: '56', name: 'Sita\'s South Indian', image: 'https://placehold.co/600x400.png', cuisine: 'Home Food, South Indian', rating: 4.9, deliveryTime: 30, priceRange: 'cheap', priceForTwo: 300, reviews: '450+', location: 'Jayanagar', distance: 2.2, opensAt: '07:30 AM', tags: ['Homemade', 'Pure Veg'] },
  { id: '57', name: 'Vikram\'s Healthy Bowls', image: 'https://placehold.co/600x400.png', cuisine: 'Home Food, Healthy', rating: 5.0, deliveryTime: 30, priceRange: 'moderate', priceForTwo: 650, reviews: '120+', location: 'Koramangala', distance: 3.8, opensAt: '10:00 AM', tags: ['Homemade', 'Healthy'] },
  { id: '58', name: 'Nisha\'s Nook', image: 'https://placehold.co/600x400.png', cuisine: 'Home Food, Bengali', rating: 4.7, deliveryTime: 50, priceRange: 'moderate', priceForTwo: 500, reviews: '80+', location: 'Marathahalli', distance: 8.5, opensAt: '12:00 PM', tags: ['Homemade'] },
  { id: '59', name: 'The Daily Dabba', image: 'https://placehold.co/600x400.png', cuisine: 'Home Food, Thali', rating: 4.8, deliveryTime: 35, priceRange: 'cheap', priceForTwo: 280, reviews: '500+', location: 'Multiple', distance: 3.5, opensAt: '11:00 AM', tags: ['Homemade'] },
  { id: '60', name: 'Fatima\'s Flavors', image: 'https://placehold.co/600x400.png', cuisine: 'Home Food, Mughlai', rating: 4.8, deliveryTime: 45, priceRange: 'moderate', priceForTwo: 750, reviews: '110+', location: 'Indiranagar', distance: 5.1, opensAt: '01:00 PM', tags: ['Homemade'] },
  { id: '61', name: 'Keto Kitchen by Aarti', image: 'https://placehold.co/600x400.png', cuisine: 'Home Food, Keto, Healthy', rating: 4.9, deliveryTime: 40, priceRange: 'expensive', priceForTwo: 900, reviews: '90+', location: 'HSR Layout', distance: 6.2, opensAt: '10:30 AM', tags: ['Homemade', 'Healthy'] },
  { id: '62', name: 'Mani\'s Meals', image: 'https://placehold.co/600x400.png', cuisine: 'Home Food, Chettinad', rating: 4.7, deliveryTime: 40, priceRange: 'moderate', priceForTwo: 600, reviews: '130+', location: 'Malleshwaram', distance: 5.8, opensAt: '12:00 PM', tags: ['Homemade'] },
  { id: '63', name: 'The Organic Homely', image: 'https://placehold.co/600x400.png', cuisine: 'Home Food, Organic', rating: 4.9, deliveryTime: 35, priceRange: 'moderate', priceForTwo: 700, reviews: '160+', location: 'Whitefield', distance: 10.0, opensAt: '09:30 AM', tags: ['Homemade', 'Healthy'] },
  { id: '64', name: 'Simple Sumptuous', image: 'https://placehold.co/600x400.png', cuisine: 'Home Food, Maharashtrian', rating: 4.8, deliveryTime: 30, priceRange: 'cheap', priceForTwo: 350, reviews: '220+', location: 'Koramangala', distance: 3.1, opensAt: '11:30 AM', tags: ['Homemade'] },
  { id: '65', name: 'Grandma\'s Recipes', image: 'https://placehold.co/600x400.png', cuisine: 'Home Food, Traditional', rating: 4.9, deliveryTime: 50, priceRange: 'moderate', priceForTwo: 500, reviews: '400+', location: 'Jayanagar', distance: 2.0, opensAt: '10:00 AM', tags: ['Homemade'] },
  { id: '66', name: 'The Cozy Cookhouse', image: 'https://placehold.co/600x400.png', cuisine: 'Home Food, Comfort Food', rating: 4.8, deliveryTime: 35, priceRange: 'moderate', priceForTwo: 550, reviews: '180+', location: 'Indiranagar', distance: 4.0, opensAt: '12:00 PM', tags: ['Homemade'] },
  { id: '67', name: 'Authentic Andhra Meals', image: 'https://placehold.co/600x400.png', cuisine: 'Home Food, Andhra', rating: 4.7, deliveryTime: 40, priceRange: 'moderate', priceForTwo: 600, reviews: '250+', location: 'HSR Layout', distance: 5.7, opensAt: '12:30 PM', tags: ['Homemade'] },
  { id: '68', name: 'Kerala Kitchenette', image: 'https://placehold.co/600x400.png', cuisine: 'Home Food, Kerala', rating: 4.8, deliveryTime: 45, priceRange: 'moderate', priceForTwo: 500, reviews: '190+', location: 'Marathahalli', distance: 8.2, opensAt: '11:00 AM', tags: ['Homemade'] },
  { id: '69', name: 'The Salad Story (Home)', image: 'https://placehold.co/600x400.png', cuisine: 'Home Food, Salads', rating: 4.9, deliveryTime: 20, priceRange: 'moderate', priceForTwo: 450, reviews: '300+', location: 'Koramangala', distance: 3.3, opensAt: '10:00 AM', tags: ['Homemade', 'Healthy'] },
  { id: '70', name: 'Biryani by Ammi', image: 'https://placehold.co/600x400.png', cuisine: 'Home Food, Biryani', rating: 4.9, deliveryTime: 55, priceRange: 'moderate', priceForTwo: 800, reviews: '280+', location: 'Indiranagar', distance: 4.8, opensAt: '01:00 PM', tags: ['Homemade'] },
];

export const offers: Offer[] = [
    {
        restaurant: "La Pino'z Pizza",
        title: "Get flat ₹125 OFF*",
        subtitle: "on mouth-watering treats",
        image: "https://placehold.co/400x300.png",
        logo: "https://placehold.co/50x50.png",
        hint: "pizza cheese"
    },
    {
        restaurant: "La Pino'z Pizza",
        title: "Get flat ₹125 OFF*",
        subtitle: "on mouth-watering treats",
        image: "https://placehold.co/400x300.png",
        logo: "https://placehold.co/50x50.png",
        hint: "pizza cheese"
    },
    {
        restaurant: "La Pino'z Pizza",
        title: "Get flat ₹125 OFF*",
        subtitle: "on mouth-watering treats",
        image: "https://placehold.co/400x300.png",
        logo: "https://placehold.co/50x50.png",
        hint: "pizza cheese"
    }
];

export const mockOrderHistory: Order[] = [
    { 
        restaurantName: 'Biryani Blues', 
        cuisine: 'Biryani', 
        date: new Date().toISOString(), 
        status: 'Active',
        items: ['Chicken Biryani', 'Coke'],
        orderType: 'Delivery',
    },
    { 
        restaurantName: 'The Sandwich Shop', 
        cuisine: 'American', 
        date: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(), 
        status: 'Active',
        items: ['Veggie Sandwich', 'Fries'],
        orderType: 'Takeaway',
    },
     { 
        restaurantName: 'Chetana Veg Restaurant', 
        cuisine: 'North Indian, Gujarati', 
        date: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(), 
        status: 'Active',
        items: ['Gujarati Thali'],
        orderType: 'Dine-in',
    },
    { 
        restaurantName: 'The Table', 
        cuisine: 'European, Continental', 
        date: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(), 
        status: 'Active',
        items: ['Table for 2'],
        orderType: 'Booking',
    },
    { 
        restaurantName: 'PVR Cafe', 
        cuisine: 'Fast Food, Beverages', 
        date: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(), 
        status: 'Active',
        items: ['Popcorn', 'Table for 4'],
        orderType: 'Booking with Pre-order',
    },
    { 
        restaurantName: 'Royal Spice', 
        cuisine: 'North Indian', 
        date: '2024-05-01', 
        status: 'Completed',
        items: ['Paneer Butter Masala', 'Naan'],
        orderType: 'Dine-in',
    },
    { 
        restaurantName: 'Pizza Heaven', 
        cuisine: 'Italian', 
        date: '2024-05-10', 
        status: 'Completed',
        items: ['Margherita Pizza', 'Garlic Bread'],
        orderType: 'Delivery',
    },
    { 
        restaurantName: 'Wok & Roll', 
        cuisine: 'Chinese', 
        date: '2024-05-20', 
        status: 'Cancelled',
        items: ['Hakka Noodles'],
        orderType: 'Takeaway',
    },
];

export const reviews: Review[] = [
  {
    id: 'r1',
    restaurantId: '1',
    author: 'Ananya Sharma',
    avatar: 'https://placehold.co/100x100.png',
    rating: 5,
    date: '2 days ago',
    content: 'Absolutely amazing food! The Butter Chicken was to die for. The service was excellent and the ambiance was lovely. Will definitely be visiting again soon!',
    likes: 12,
    images: ['https://placehold.co/200x200.png', 'https://placehold.co/200x200.png'],
  },
  {
    id: 'r2',
    restaurantId: '1',
    author: 'Rohan Verma',
    avatar: 'https://placehold.co/100x100.png',
    rating: 4,
    date: '1 week ago',
    content: 'Had a great time at Royal Spice. The kebabs were succulent and flavorful. The main course was good too, but a bit too spicy for my taste. Overall, a good experience.',
    likes: 5,
  },
  {
    id: 'r3',
    restaurantId: '1',
    author: 'Priya Singh',
    avatar: 'https://placehold.co/100x100.png',
    rating: 5,
    date: '3 weeks ago',
    content: 'One of the best North Indian restaurants in Bangalore. Every dish we ordered was delicious. The staff is very courteous and helpful. Highly recommended!',
    likes: 25,
     images: ['https://placehold.co/200x200.png'],
  },
  {
    id: 'r4',
    restaurantId: '2',
    author: 'Sameer Khan',
    avatar: 'https://placehold.co/100x100.png',
    rating: 4,
    date: '1 month ago',
    content: 'Pizza Heaven is my go-to place for pizzas. Their thin-crust pizzas are the best. The BOGO offer is a great deal. The only downside is that it can get a bit crowded on weekends.',
    likes: 8,
  },
  {
    id: 'r5',
    restaurantId: '2',
    author: 'Neha Gupta',
    avatar: 'https://placehold.co/100x100.png',
    rating: 5,
    date: '2 months ago',
    content: 'Loved the pizzas here! We tried the Farmhouse and the Pepperoni pizzas, and both were delicious. The staff was friendly and the service was quick. A must-visit for pizza lovers!',
    likes: 15,
  },
];

export const transactions: WalletTransaction[] = [
  {
    id: 1,
    type: 'credit',
    title: 'Cashback from Royal Spice',
    description: 'Order #12345',
    amount: 50,
    date: '2024-08-15',
    expiryDate: '2024-09-15',
  },
  {
    id: 2,
    type: 'credit',
    title: 'Welcome Bonus',
    description: 'First order offer',
    amount: 100,
    date: '2024-08-12',
    expiryDate: '2024-09-12',
  },
   {
    id: 3,
    type: 'debit',
    title: 'Paid for Order #12301',
    description: 'Burger Barn',
    amount: -75,
    date: '2024-08-11',
  },
  {
    id: 4,
    type: 'credit',
    title: 'Cashback from Pizza Heaven',
    description: 'Order #12300',
    amount: 75,
    date: '2024-08-10',
    expiryDate: '2024-09-10',
  },
  {
    id: 5,
    type: 'credit',
    title: 'Reward Unlocked',
    description: 'From Treasure Hunt',
    amount: 50,
    date: '2024-08-09',
    expiryDate: '2024-09-09',
  },
  {
    id: 6,
    type: 'credit',
    title: 'Reward Unlocked',
    description: 'From Treasure Hunt',
    amount: 20,
    date: '2024-08-08',
    expiryDate: '2024-09-08',
  },
  {
    id: 7,
    type: 'credit',
    title: 'Reward Unlocked',
    description: 'From Treasure Hunt',
    amount: 100,
    date: '2024-08-07',
    expiryDate: '2024-09-07',
  },
];
